### PR TITLE
use formatters

### PR DESCRIPTION
**Pull request by agoddard**
move adjudicator and slack_message to formatters, deprecates kitchen-judge, kitchen-slack

### CODE REVIEW

**Comment by chrisroberts** [comment]
Please include yardoc on methods and constants (`lib/jackal-kitchen/formatter/slack_message.rb` has proper format)

**Comment by agoddard** [comment]
@chrisroberts will add now. I should also mention this is just a direct port of the previous component, this whole thing is going to get refactored when we add more metadata to the adjudication

**Comment by cwjohnston** [comment]
@chrisroberts i added some yardoc, can you take a look?

**Comment by chrisroberts** [comment]
:+1:

**Pull request merged**
